--연간 매출
SELECT SUBSTR(ODATE,1,2) as "PERIOD", SUM(O_AMOUNT) AS PERIOD_AMOUNT
FROM ORDER_BOOK OB, ORDER_DETAIL OD
WHERE OB.ONO = OD.ONO
GROUP BY SUBSTR(ODATE,1,2)
ORDER BY 1;

--월별 매출 검색(SYSDATE년도 기준)
SELECT SUBSTR(ODATE,4,2) as "PERIOD", SUM(O_AMOUNT) AS PERIOD_AMOUNT
FROM ORDER_BOOK OB, ORDER_DETAIL OD
WHERE OB.ONO = OD.ONO AND TO_CHAR(ODATE,'YY') = TO_CHAR(SYSDATE,'YY')
GROUP BY SUBSTR(ODATE,4,2) 
ORDER BY 1;

--일별 매출 검색(SYSDATE 기준)
SELECT SUBSTR(ODATE,7,2) as "PERIOD", SUM(O_AMOUNT) AS PERIOD_AMOUNT
FROM ORDER_BOOK OB, ORDER_DETAIL OD
WHERE OB.ONO = OD.ONO AND TO_CHAR(ODATE,'YY/MM') = TO_CHAR(SYSDATE,'YY/MM')
GROUP BY SUBSTR(ODATE,7,2) 
ORDER BY 1;

--전체 매출
SELECT ODATE, O_AMOUNT
FROM ORDER_BOOK OB, ORDER_DETAIL OD
WHERE OB.ONO = OD.ONO
ORDER BY 1;