UPDATE PRODUCT SET
PIMAGE = '???'
WHERE PCODE='3513';

UPDATE PRODUCT SET
PDESCRIPTION = '???'
WHERE PCODE='3513';

UPDATE PRODUCT SET
CNO = 35,
PNAME = '¿¡¾îÄÁ',
PPRICE = 100000,
PSTOCK = 20,
PDISCOUNT =0,
PREGIST =SYSDATE
WHERE PCODE ='3513';