--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-13-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CART_CNTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."CART_CNTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORY_CNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."CATEGORY_CNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 56 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CCENTER_CNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."CCENTER_CNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COUPON_CONO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."COUPON_CONO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DELIVERY_DNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."DELIVERY_DNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GRADE_GNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."GRADE_GNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ODETAIL_ONO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."ODETAIL_ONO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OD_BOOK_ODNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."OD_BOOK_ODNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_PANO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."PAYMENT_PANO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_PCODE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."PRODUCT_PCODE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_RNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BITELECTRO"."REVIEW_RNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."CART" 
   (	"CNTO" NUMBER(10,0), 
	"PCODE" VARCHAR2(30 BYTE), 
	"MID" VARCHAR2(30 BYTE), 
	"CNO" NUMBER(10,0), 
	"PCNT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."CATEGORY" 
   (	"CNO" NUMBER(10,0), 
	"CMAIN" VARCHAR2(30 BYTE), 
	"CMIDDLE" VARCHAR2(30 BYTE), 
	"CSUB" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COUPON
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."COUPON" 
   (	"CONO" NUMBER(10,0), 
	"MID" VARCHAR2(30 BYTE), 
	"CNAME" VARCHAR2(30 BYTE), 
	"CDISPER" NUMBER(10,0), 
	"CDISCASH" NUMBER(10,0), 
	"CORDATE" DATE, 
	"CVALIDITY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_CENTER
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."CUSTOMER_CENTER" 
   (	"CNO" VARCHAR2(30 BYTE), 
	"MID" VARCHAR2(30 BYTE), 
	"CSUBJECT" VARCHAR2(30 BYTE), 
	"CCONTENT" VARCHAR2(100 BYTE), 
	"CSECRET" NUMBER(1,0), 
	"CIMAGE" VARCHAR2(30 BYTE), 
	"CRDATE" DATE, 
	"CCATEGORY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DELIVERY
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."DELIVERY" 
   (	"DNO" NUMBER(10,0), 
	"DNAME" VARCHAR2(30 BYTE), 
	"DPHONE" VARCHAR2(30 BYTE), 
	"DPRICE" NUMBER(10,0), 
	"DADDRESS" VARCHAR2(100 BYTE), 
	"PARRIVE_DATE" DATE, 
	"DCLASS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRADES
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."GRADES" 
   (	"GNO" NUMBER(1,0), 
	"GNAME" VARCHAR2(30 BYTE), 
	"LOWGRADE" NUMBER(10,0), 
	"HIGHGRADE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."MEMBER" 
   (	"MID" VARCHAR2(30 BYTE), 
	"MPW" VARCHAR2(30 BYTE), 
	"MNAME" VARCHAR2(30 BYTE), 
	"MPHONE" VARCHAR2(30 BYTE), 
	"MADDRESS" VARCHAR2(200 BYTE), 
	"MJUMIN" VARCHAR2(30 BYTE), 
	"MEMAIL" VARCHAR2(150 BYTE), 
	"MPOINT" NUMBER(10,0), 
	"MCUMULATIVE_BUY" NUMBER(10,0), 
	"MJOINDATE" DATE, 
	"MCLASS" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_BOOK
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."ORDER_BOOK" 
   (	"ODNO" NUMBER(10,0), 
	"ONO" NUMBER(10,0), 
	"PCODE" VARCHAR2(30 BYTE), 
	"CNO" NUMBER(10,0), 
	"PCNT" NUMBER(10,0), 
	"PPRICE" NUMBER(10,0), 
	"PSTATUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAIL
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."ORDER_DETAIL" 
   (	"ONO" NUMBER(10,0), 
	"MID" VARCHAR2(30 BYTE), 
	"DNO" NUMBER(10,0), 
	"ODATE" DATE, 
	"O_AMOUNT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."PAYMENT" 
   (	"PANO" NUMBER(10,0), 
	"ONO" NUMBER(10,0), 
	"PRODUCT_ALL_PAY" NUMBER(10,0), 
	"DISCOUNT" NUMBER(10,0), 
	"COUPONDISCOUNT" NUMBER(10,0), 
	"USEPOINT" NUMBER(10,0), 
	"PURCHASE_AMOUNT" NUMBER(10,0), 
	"PCLASS" NUMBER(30,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."PRODUCT" 
   (	"PCODE" VARCHAR2(30 BYTE), 
	"CNO" NUMBER(10,0), 
	"PNAME" VARCHAR2(30 BYTE), 
	"PPRICE" NUMBER(10,0), 
	"PIMAGE" VARCHAR2(30 BYTE), 
	"PSTOCK" NUMBER(10,0), 
	"PDESCRIPTION" VARCHAR2(500 BYTE), 
	"PDISCOUNT" NUMBER(10,0), 
	"PREGIST" DATE, 
	"PCUMULATIVE_SALES" NUMBER(10,0), 
	"PREATING" NUMBER(5,0), 
	"PREVIEW_COUNT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "BITELECTRO"."REVIEW" 
   (	"RNO" NUMBER(10,0), 
	"MID" VARCHAR2(30 BYTE), 
	"PCODE" VARCHAR2(30 BYTE), 
	"CNO" NUMBER(10,0), 
	"RIMAGE" VARCHAR2(30 BYTE), 
	"RSTAR" NUMBER(10,0), 
	"RCONTENT" VARCHAR2(500 BYTE), 
	"RDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BITELECTRO.CART
SET DEFINE OFF;
REM INSERTING into BITELECTRO.CATEGORY
SET DEFINE OFF;
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (2,'대형가전','TV/영상가전','TV');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (3,'대형가전','TV/영상가전','TV');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (4,'대형가전','TV/영상가전','미니빔/사운드바');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (5,'대형가전','TV/영상가전','장식장/TV악세사리');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (6,'대형가전','TV/영상가전','디지털액자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (7,'대형가전','냉장고','양문형냉장고');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (8,'대형가전','냉장고','일반냉장고');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (9,'대형가전','냉장고','미니/차량용냉장고');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (10,'대형가전','냉장고','업소용냉장고');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (11,'대형가전','냉장고','김치냉장고');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (12,'대형가전','세탁기','일반세탁기');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (13,'대형가전','세탁기','드럼세탁기');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (14,'대형가전','세탁기','탈수기');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (15,'대형가전','의류건조기','의류건조기');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (16,'계절가전','에어컨','스탠드형');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (17,'계절가전','에어컨','벽걸이형');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (18,'계절가전','에어컨','에어컨용품');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (19,'계절가전','제습기','제습기');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (21,'계절가전','선풍기','스탠드형');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (22,'계절가전','선풍기','벽걸이형');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (23,'계절가전','선풍기','미니선풍기');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (24,'컴퓨터','컴퓨터','노트북');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (25,'컴퓨터','컴퓨터','데스크탑');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (26,'컴퓨터','컴퓨터','모니터');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (27,'컴퓨터','컴퓨터','태블릿PC');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (28,'컴퓨터','PC부품','CPU');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (29,'컴퓨터','PC부품','RAM');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (30,'컴퓨터','PC부품','메인보드');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (31,'컴퓨터','PC부품','그래픽카드');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (32,'컴퓨터','PC부품','사운드카드');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (33,'컴퓨터','PC부품','파워');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (34,'컴퓨터','PC부품','쿨러');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (35,'카메라','카메라','DSLR');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (36,'카메라','카메라','미러리스');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (37,'카메라','카메라','디지털카메라');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (38,'카메라','카메라','액션캠/캠코더');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (39,'카메라','카메라','웹캠/CCTV');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (40,'휴대폰','SKT','삼성전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (41,'휴대폰','SKT','APPLE');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (42,'휴대폰','SKT','LG전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (43,'휴대폰','SKT','기타');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (44,'휴대폰','KT','삼성전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (45,'휴대폰','KT','APPLE');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (46,'휴대폰','KT','LG전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (47,'휴대폰','KT','기타');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (48,'휴대폰','LG','삼성전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (49,'휴대폰','LG','APPLE');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (50,'휴대폰','LG','LG전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (51,'휴대폰','LG','기타');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (52,'휴대폰','알뜰폰','삼성전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (53,'휴대폰','알뜰폰','APPLE');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (54,'휴대폰','알뜰폰','LG전자');
Insert into BITELECTRO.CATEGORY (CNO,CMAIN,CMIDDLE,CSUB) values (55,'휴대폰','알뜰폰','기타');
REM INSERTING into BITELECTRO.COUPON
SET DEFINE OFF;
REM INSERTING into BITELECTRO.CUSTOMER_CENTER
SET DEFINE OFF;
REM INSERTING into BITELECTRO.DELIVERY
SET DEFINE OFF;
REM INSERTING into BITELECTRO.GRADES
SET DEFINE OFF;
REM INSERTING into BITELECTRO.MEMBER
SET DEFINE OFF;
Insert into BITELECTRO.MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MJUMIN,MEMAIL,MPOINT,MCUMULATIVE_BUY,MJOINDATE,MCLASS) values ('test3','test3333','테스트셋','33-33','인천시','3333333333333',null,0,0,to_date('21/10/13','RR/MM/DD'),1);
Insert into BITELECTRO.MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MJUMIN,MEMAIL,MPOINT,MCUMULATIVE_BUY,MJOINDATE,MCLASS) values ('test1','test1111','테스트하나','11-11-11','서울','1111111111111',null,0,0,to_date('21/10/13','RR/MM/DD'),1);
Insert into BITELECTRO.MEMBER (MID,MPW,MNAME,MPHONE,MADDRESS,MJUMIN,MEMAIL,MPOINT,MCUMULATIVE_BUY,MJOINDATE,MCLASS) values ('test2','2222','테스트둘','222-2222-2222','인천시','2222222222222','test2@test.com',0,0,to_date('21/10/13','RR/MM/DD'),0);
REM INSERTING into BITELECTRO.ORDER_BOOK
SET DEFINE OFF;
REM INSERTING into BITELECTRO.ORDER_DETAIL
SET DEFINE OFF;
REM INSERTING into BITELECTRO.PAYMENT
SET DEFINE OFF;
REM INSERTING into BITELECTRO.PRODUCT
SET DEFINE OFF;
Insert into BITELECTRO.PRODUCT (PCODE,CNO,PNAME,PPRICE,PIMAGE,PSTOCK,PDESCRIPTION,PDISCOUNT,PREGIST,PCUMULATIVE_SALES,PREATING,PREVIEW_COUNT) values ('25',2,'삼성TV',200000,null,10,null,null,to_date('21/10/13','RR/MM/DD'),0,0,0);
REM INSERTING into BITELECTRO.REVIEW
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_CART" ON "BITELECTRO"."CART" ("CNTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_CATEGORY" ON "BITELECTRO"."CATEGORY" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_COUPON
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_COUPON" ON "BITELECTRO"."COUPON" ("CONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CUSTOMER_CENTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_CUSTOMER_CENTER" ON "BITELECTRO"."CUSTOMER_CENTER" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DELIVERY
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_DELIVERY" ON "BITELECTRO"."DELIVERY" ("DNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_GRADES
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_GRADES" ON "BITELECTRO"."GRADES" ("GNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ORDER_BOOK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_ORDER_BOOK" ON "BITELECTRO"."ORDER_BOOK" ("ODNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ORDER_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_ORDER_DETAIL" ON "BITELECTRO"."ORDER_DETAIL" ("ONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PAYMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_PAYMENT" ON "BITELECTRO"."PAYMENT" ("PANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_PRODUCT" ON "BITELECTRO"."PRODUCT" ("PCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."PK_REVIEW" ON "BITELECTRO"."REVIEW" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007050
--------------------------------------------------------

  CREATE UNIQUE INDEX "BITELECTRO"."SYS_C007050" ON "BITELECTRO"."MEMBER" ("MID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CNTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."CART" MODIFY ("CNO" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."CART" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."CART" MODIFY ("PCODE" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."CART" MODIFY ("CNTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("CNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."CATEGORY" MODIFY ("CNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COUPON
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY ("CONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."COUPON" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."COUPON" MODIFY ("CONO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER_CENTER
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."CUSTOMER_CENTER" ADD CONSTRAINT "PK_CUSTOMER_CENTER" PRIMARY KEY ("CNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."CUSTOMER_CENTER" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."CUSTOMER_CENTER" MODIFY ("CNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DELIVERY
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."DELIVERY" ADD CONSTRAINT "PK_DELIVERY" PRIMARY KEY ("DNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."DELIVERY" MODIFY ("DNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRADES
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."GRADES" ADD CONSTRAINT "PK_GRADES" PRIMARY KEY ("GNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."GRADES" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."MEMBER" ADD PRIMARY KEY ("MID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."MEMBER" MODIFY ("MID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_BOOK
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."ORDER_BOOK" ADD CONSTRAINT "PK_ORDER_BOOK" PRIMARY KEY ("ODNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."ORDER_BOOK" MODIFY ("CNO" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."ORDER_BOOK" MODIFY ("PCODE" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."ORDER_BOOK" MODIFY ("ONO" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."ORDER_BOOK" MODIFY ("ODNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."ORDER_DETAIL" ADD CONSTRAINT "PK_ORDER_DETAIL" PRIMARY KEY ("ONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."ORDER_DETAIL" MODIFY ("DNO" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."ORDER_DETAIL" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."ORDER_DETAIL" MODIFY ("ONO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."PAYMENT" MODIFY ("ONO" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."PAYMENT" MODIFY ("PANO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."PRODUCT" MODIFY ("CNO" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."PRODUCT" MODIFY ("PCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BITELECTRO"."REVIEW" MODIFY ("CNO" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."REVIEW" MODIFY ("PCODE" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."REVIEW" MODIFY ("MID" NOT NULL ENABLE);
  ALTER TABLE "BITELECTRO"."REVIEW" MODIFY ("RNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."CART" ADD CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY ("MID")
	  REFERENCES "BITELECTRO"."MEMBER" ("MID") ENABLE;
  ALTER TABLE "BITELECTRO"."CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART_1" FOREIGN KEY ("PCODE")
	  REFERENCES "BITELECTRO"."PRODUCT" ("PCODE") ENABLE;
  ALTER TABLE "BITELECTRO"."CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART_2" FOREIGN KEY ("CNO")
	  REFERENCES "BITELECTRO"."CATEGORY" ("CNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COUPON
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."COUPON" ADD CONSTRAINT "FK_MEMBER_TO_COUPON_1" FOREIGN KEY ("MID")
	  REFERENCES "BITELECTRO"."MEMBER" ("MID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_CENTER
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."CUSTOMER_CENTER" ADD CONSTRAINT "FK_MEMBER_TO_CUSTOMER_CENTER_1" FOREIGN KEY ("MID")
	  REFERENCES "BITELECTRO"."MEMBER" ("MID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_BOOK
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."ORDER_BOOK" ADD CONSTRAINT "FK_ORDER_DETAIL_TO_O_BOOK_1" FOREIGN KEY ("ONO")
	  REFERENCES "BITELECTRO"."ORDER_DETAIL" ("ONO") ENABLE;
  ALTER TABLE "BITELECTRO"."ORDER_BOOK" ADD CONSTRAINT "FK_PRODUCT_TO_ORDER_BOOK_1" FOREIGN KEY ("PCODE")
	  REFERENCES "BITELECTRO"."PRODUCT" ("PCODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."ORDER_DETAIL" ADD CONSTRAINT "FK_DELIVERY_TO_ORDER_DETAIL_1" FOREIGN KEY ("DNO")
	  REFERENCES "BITELECTRO"."DELIVERY" ("DNO") ENABLE;
  ALTER TABLE "BITELECTRO"."ORDER_DETAIL" ADD CONSTRAINT "FK_MEMBER_TO_ORDER_DETAIL_1" FOREIGN KEY ("MID")
	  REFERENCES "BITELECTRO"."MEMBER" ("MID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."PAYMENT" ADD CONSTRAINT "FK_ORDER_DETAIL_TO_PAYMENT_1" FOREIGN KEY ("ONO")
	  REFERENCES "BITELECTRO"."ORDER_DETAIL" ("ONO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."PRODUCT" ADD CONSTRAINT "FK_CATEGORY_TO_PRODUCT_1" FOREIGN KEY ("CNO")
	  REFERENCES "BITELECTRO"."CATEGORY" ("CNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "BITELECTRO"."REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY ("MID")
	  REFERENCES "BITELECTRO"."MEMBER" ("MID") ENABLE;
  ALTER TABLE "BITELECTRO"."REVIEW" ADD CONSTRAINT "FK_PRODUCT_TO_REVIEW_1" FOREIGN KEY ("PCODE")
	  REFERENCES "BITELECTRO"."PRODUCT" ("PCODE") ENABLE;
