CREATE TABLE MEMBER (
   MID   VARCHAR2(30) PRIMARY KEY   NOT NULL,
   MPW   VARCHAR2(30)   NULL,
   MNAME   VARCHAR2(30)   NULL,
   MPHONE   VARCHAR2(30)   NULL,
   MADDRESS   VARCHAR2(200)   NULL,
   MBIRTH   DATE   NULL,
   MEMAIL   VARCHAR2(150)   NULL,
   MGENDER   VARCHAR2(30)   NULL,
   MPOINT   NUMBER(10)   NULL,
   MCUMULATIVE_BUY   NUMBER(10)   NULL,
   MJOINDATE   DATE   NULL,
   MCLASS   NUMBER(5)   NULL
);

CREATE TABLE ORDER_DETAIL (
   ONO   NUMBER(10)   NOT NULL,
   MID   VARCHAR2(30)   NOT NULL,
   DNO   NUMBER(10)   NOT NULL,
   ODATE   DATE   NULL,
   O_AMOUNT   NUMBER(10)   NULL
);

CREATE TABLE CART (
   CNTO   NUMBER(10)   NOT NULL,
   PCODE   VARCHAR2(30)   NOT NULL,
   MID   VARCHAR2(30)   NOT NULL,
   CNO   NUMBER(10)   NOT NULL,
   PCNT   NUMBER(10)   NULL
);

CREATE TABLE REVIEW (
   RNO   NUMBER(10)   NOT NULL,
   MID   VARCHAR2(30)   NOT NULL,
   PCODE   VARCHAR2(30)   NOT NULL,
   CNO   NUMBER(10)   NOT NULL,
   RIMAGE   VARCHAR2(30)   NULL,
   RSTAR   NUMBER(10)   NULL,
   RCONTENT   VARCHAR2(500)   NULL,
   RDATE   DATE   NULL
);

CREATE TABLE PAYMENT (
   PANO   NUMBER(10)   NOT NULL,
   ONO   NUMBER(10)   NOT NULL,
   PRODUCT_ALL_PAY   NUMBER(10)   NULL,
   DISCOUNT   NUMBER(10)   NULL,
   COUPONDISCOUNT   NUMBER(10)   NULL,
   USEPOINT   NUMBER(10)   NULL,
   PURCHASE_AMOUNT   NUMBER(10)   NULL,
   PCLASS   NUMBER(30)   NULL
);

CREATE TABLE CUSTOMER_CENTER (
   CNO   VARCHAR2(30)   NOT NULL,
   MID   VARCHAR2(30)   NOT NULL,
   CSUBJECT   VARCHAR2(30)   NULL,
   CCONTENT   VARCHAR2(100)   NULL,
   CSECRET   NUMBER(1)   NULL,
   CIMAGE   VARCHAR2(30)   NULL,
   CRDATE   DATE   NULL,
   CCATEGORY   VARCHAR(255)   NULL
);

CREATE TABLE ORDER_BOOK (
   ODNO   NUMBER(10)   NOT NULL,
   ONO   NUMBER(10)   NOT NULL,
   PCODE   VARCHAR2(30)   NOT NULL,
   CNO   NUMBER(10)   NOT NULL,
   PCNT   NUMBER(10)   NULL,
   PPRICE   NUMBER(10)   NULL,
   PSTATUS   VARCHAR2(30)   NULL
);

CREATE TABLE GRADES (
   GNO   NUMBER(1)   NOT NULL,
   GNAME   VARCHAR2(30)   NULL,
   LOWGRADE   NUMBER(10)   NULL,
   HIGHGRADE   NUMBER(10)   NULL
);

CREATE TABLE DELIVERY (
   DNO   NUMBER(10)   NOT NULL,
   DNAME   VARCHAR2(30)   NULL,
   DPHONE   VARCHAR2(30)   NULL,
   DPRICE   NUMBER(10)   NULL,
   DADDRESS   VARCHAR2(100)   NULL,
   PARRIVE_DATE   DATE   NULL,
   DCLASS   VARCHAR2(100)   NULL
);

CREATE TABLE COUPON (
   CONO   NUMBER(10)   NOT NULL,
   MID   VARCHAR2(30)   NOT NULL,
   CNAME   VARCHAR2(30)   NULL,
   CDISPER   NUMBER(10)   NULL,
   CDISCASH   NUMBER(10)   NULL,
   CORDATE   DATE   NULL,
   CVALIDITY   NUMBER(10)   NULL
);

CREATE TABLE CATEGORY (
   CNO   NUMBER(10)   NOT NULL,
   CMAIN   VARCHAR2(30)   NULL,
   CMIDDLE   VARCHAR2(30)   NULL,
   CSUB   VARCHAR2(30)   NULL
);

CREATE TABLE PRODUCT (
   PCODE   VARCHAR2(30)   NOT NULL,
   CNO   NUMBER(10)   NOT NULL,
   PNAME   VARCHAR2(30)   NULL,
   PPRICE   NUMBER(10)   NULL,
   PIMAGE   VARCHAR2(30)   NULL,
   PSTOCK   NUMBER(10)   NULL,
   PDESCRIPTION   VARCHAR2(500)   NULL,
   PDISCOUNT   NUMBER(10)   NULL,
   PREGIST   DATE   NULL,
   PCUMULATIVE_SALES   NUMBER(10)   NULL,
   PREATING   NUMBER(5)   NULL,
   PREVIEW_COUNT   NUMBER(10)   NULL
);



ALTER TABLE ORDER_DETAIL ADD CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (
   ONO
);

ALTER TABLE CART ADD CONSTRAINT PK_CART PRIMARY KEY (
   CNTO
);

ALTER TABLE REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY (
   RNO
);

ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (
   PANO
);

ALTER TABLE CUSTOMER_CENTER ADD CONSTRAINT PK_CUSTOMER_CENTER PRIMARY KEY (
   CNO
);

ALTER TABLE ORDER_BOOK ADD CONSTRAINT PK_ORDER_BOOK PRIMARY KEY (
   ODNO
);

ALTER TABLE GRADES ADD CONSTRAINT PK_GRADES PRIMARY KEY (
   GNO
);

ALTER TABLE DELIVERY ADD CONSTRAINT PK_DELIVERY PRIMARY KEY (
   DNO
);

ALTER TABLE COUPON ADD CONSTRAINT PK_COUPON PRIMARY KEY (
   CONO
);

ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (
   CNO
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
   PCODE
);

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_MEMBER_TO_ORDER_DETAIL_1 FOREIGN KEY (
   MID
)
REFERENCES MEMBER (
   MID
);

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_DELIVERY_TO_ORDER_DETAIL_1 FOREIGN KEY (
   DNO
)
REFERENCES DELIVERY (
   DNO
);

ALTER TABLE CART ADD CONSTRAINT FK_PRODUCT_TO_CART_1 FOREIGN KEY (
   PCODE
)
REFERENCES PRODUCT (
   PCODE
);

ALTER TABLE CART ADD CONSTRAINT FK_PRODUCT_TO_CART_2 FOREIGN KEY (
   CNO
)
REFERENCES CATEGORY (
   CNO 
);

ALTER TABLE CART ADD CONSTRAINT FK_MEMBER_TO_CART_1 FOREIGN KEY (
   MID
)
REFERENCES MEMBER (
   MID
);

ALTER TABLE REVIEW ADD CONSTRAINT FK_MEMBER_TO_REVIEW_1 FOREIGN KEY (
   MID
)
REFERENCES MEMBER (
   MID
);

ALTER TABLE REVIEW ADD CONSTRAINT FK_PRODUCT_TO_REVIEW_1 FOREIGN KEY (
   PCODE
)
REFERENCES PRODUCT (
   PCODE
);


ALTER TABLE PAYMENT ADD CONSTRAINT FK_ORDER_DETAIL_TO_PAYMENT_1 FOREIGN KEY (
   ONO
)
REFERENCES ORDER_DETAIL (
   ONO
);

ALTER TABLE CUSTOMER_CENTER ADD CONSTRAINT FK_MEMBER_TO_CUSTOMER_CENTER_1 FOREIGN KEY (
   MID
)
REFERENCES MEMBER (
   MID
);

ALTER TABLE ORDER_BOOK ADD CONSTRAINT FK_ORDER_DETAIL_TO_O_BOOK_1 FOREIGN KEY (
   ONO
)
REFERENCES ORDER_DETAIL (
   ONO
);

ALTER TABLE ORDER_BOOK ADD CONSTRAINT FK_PRODUCT_TO_ORDER_BOOK_1 FOREIGN KEY (
   PCODE
)
REFERENCES PRODUCT (
   PCODE
);

ALTER TABLE COUPON ADD CONSTRAINT FK_MEMBER_TO_COUPON_1 FOREIGN KEY (
   MID
)
REFERENCES MEMBER (
   MID
);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_CATEGORY_TO_PRODUCT_1 FOREIGN KEY (
   CNO
)
REFERENCES CATEGORY (
   CNO
);

CREATE SEQUENCE CART_CNTO_SEQ NOCACHE;
CREATE SEQUENCE CATEGORY_CNO_SEQ NOCACHE;
CREATE SEQUENCE COUPON_CONO_SEQ NOCACHE;
CREATE SEQUENCE CCENTER_CNO_SEQ NOCACHE;
CREATE SEQUENCE DELIVERY_DNO_SEQ NOCACHE;
CREATE SEQUENCE GRADE_GNO_SEQ NOCACHE;
CREATE SEQUENCE OD_BOOK_ODNO_SEQ NOCACHE;
CREATE SEQUENCE ODETAIL_ONO_SEQ NOCACHE;
CREATE SEQUENCE PAYMENT_PANO_SEQ NOCACHE;
CREATE SEQUENCE REVIEW_RNO_SEQ NOCACHE;

SELECT * FROM MEMBER
WHERE MCLASS >= 1;

INSERT INTO MEMBER 
VALUES ('test4', '4444', '테스트4', '444-4444-4444', '안양시', TO_DATE('19990202'), 'test4@test.com', 'male', 0, 0, SYSDATE, 1);

ALTER TABLE MEMBER RENAME COLUMN MBIRTH TO MJUMIN; --MBIRTH -> MJUMIN변경
ALTER TABLE MEMBER MODIFY MJUMIN VARCHAR2(20); -- MJUMIN 데이터타입 VARCHAR2
ALTER TABLE MEMBER DROP COLUMN MGENDER;  --MGENDER 컬럼 삭제
commit;

SELECT * FROM MEMBER WHERE MCLASS <= 1;